[workspace]
resolver = "2"
members = [

]

[package]
name = "apollo"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["Jacob Hoeflaken <jhoeflaken@live.nl>"]
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
